version: '3.8'

services:
  webapp:
    image: bakiiakarr/paytak:20.00
    build: .
    ports:
      - "8080:8080"
    env_file:
      - ./Paytak/.env
    networks:
      - paytak-network

networks:
  paytak-network:
    driver: bridge
